### ISSUE TITLE
analysis Folder

### ISSUE THREAD

**Issue by noorazhaoz** [paidamoyo/counterfactual_survival_analysis#1]
Hi,

Thanks for publishing this project!

After I train the model and I l'd like to calculate both causal and factual metrics, and the path made me confused,

FileNotFoundError: [Errno 2] No such file or directory: 'analysis/actg175_simulated/alpha_100/CSA-INFO/Valid_pred_t0_F.npy'

**Comment by paidamoyo** [comment]
Hi,

Please replace the path with your local path.
